title: Alexander Ek - Postdoctoral Research Fellow
description: Alexander Ek Postdoctoral Research Fellow Statistics Combinatorial Optimisation Optimization
url: https://jekyll-cv.stavrospanakakis.com
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
